# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/
# Benjamin google_analytics: 'UA-45631879-2' delted from below


# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: EducationalOrganization
    local_business_type: ''
    org_name: 'University of Chicago'
    description: 'Introductory course to reproducible research and programming in the social sciences.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: 'Created by Sabrina Nardin based on Â© {year} Benjamin Soltoff website licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: false
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    theme_light: paraiso-light
    theme_dark: paraiso-dark
    extra_languages:
      - r
      - latex
  math:
    enable: true
  privacy_pack:
    enable: true
  repository:
    url: 'https://github.com/css-materials/course-site'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: '2'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
